# Legacy Application Analysis Schema Configuration
# This file defines the allowed nodes and relationships for legacy application modernization analysis

# Node types allowed in the knowledge graph
allowed_nodes:
  # System Architecture
  - System
  - Application
  - Service
  - Component
  - Module
  - Library
  - Framework
  
  # Code Entities
  - Program
  - Function
  - Procedure
  - Class
  - Method
  - Interface
  - Package
  - Namespace
  
  # Data Entities
  - Database
  - Table
  - View
  - Index
  - Schema
  - File
  - DataSource
  - Repository
  
  # Infrastructure
  - Server
  - Configuration
  - Environment
  - Deployment
  
  # Business Entities
  - BusinessEntity
  - BusinessProcess
  - BusinessRule
  - Domain
  - Workflow
  
  # Documentation
  - Document
  - Specification
  - UserGuide
  - API
  - Contract
  
  # Legacy Mainframe
  - Job
  - BatchProgram
  - ScreenMap
  - Transaction
  - Dataset
  - Copybook

# Relationship types allowed in the knowledge graph
# Format: Triple relationships as [source_node, relationship_type, target_node]
# This provides precise control over which node types can be connected
allowed_relationships:
  # System Architecture relationships
  - [System, CONTAINS, Application]
  - [System, CONTAINS, Service]
  - [Application, CONTAINS, Component]
  - [Application, CONTAINS, Module]
  - [Component, CONTAINS, Class]
  - [Component, CONTAINS, Function]
  - [Module, CONTAINS, Function]
  - [Module, CONTAINS, Class]
  
  # Dependency relationships
  - [Application, DEPENDS_ON, System]
  - [Service, DEPENDS_ON, Application]
  - [Component, DEPENDS_ON, Library]
  - [Component, DEPENDS_ON, Framework]
  - [Module, IMPORTS, Module]
  - [Class, EXTENDS, Class]
  - [Class, IMPLEMENTS, Interface]
  - [Function, CALLS, Function]
  - [Procedure, CALLS, Procedure]
  - [Method, CALLS, Method]
  
  # Data relationships
  - [Application, READS_FROM, Database]
  - [Application, WRITES_TO, Database]
  - [Service, ACCESSES, Table]
  - [Component, USES, DataSource]
  - [Function, MODIFIES, File]
  - [Program, STORES_IN, Repository]
  - [BatchProgram, READS_FROM, Dataset]
  - [BatchProgram, WRITES_TO, Dataset]
  
  # Legacy Mainframe relationships
  - [Job, CONTAINS, BatchProgram]
  - [Transaction, USES, ScreenMap]
  - [BatchProgram, USES, Copybook]
  - [Program, INCLUDES, Copybook]
  - [ScreenMap, REFERENCES, Table]
  
  # Business relationships
  - [BusinessProcess, MANAGES, BusinessEntity]
  - [Workflow, PROCESSES, BusinessEntity]
  - [Application, SUPPORTS, BusinessProcess]
  - [Service, HANDLES, BusinessRule]
  - [Component, SERVES, Domain]
  
  # Infrastructure relationships
  - [Application, DEPLOYED_ON, Server]
  - [Service, RUNS_ON, Environment]
  - [Configuration, CONFIGURES, Application]
  - [Deployment, TARGETS, Server]
  
  # Documentation relationships
  - [Document, DESCRIBES, Application]
  - [Document, DESCRIBES, System]
  - [Specification, SPECIFIES, Component]
  - [UserGuide, DOCUMENTS, API]
  - [Contract, DEFINES, Interface]
  
  # Code Structure relationships
  - [Package, CONTAINS, Class]
  - [Package, CONTAINS, Interface]
  - [Namespace, CONTAINS, Function]
  - [Class, CONTAINS, Method]
  - [Interface, DEFINES, Method]
  
  # Configuration and Control
  - [Configuration, CONTROLS, Service]
  - [Environment, DEFINES, Configuration]