# Oracle Forms and PL/SQL Analysis Schema Configuration
# This file defines the allowed nodes and relationships for Oracle Forms and PL/SQL application analysis

# Node types allowed in the knowledge graph
allowed_nodes:
  # Oracle Forms Entities
  - OracleForm
  - FormBlock
  - FormItem
  - FormCanvas
  - FormTrigger
  - FormWindow
  - FormLOV
  - FormAlert
  - FormParameter
  
  # Oracle Forms Libraries and Menus
  - OracleLibrary
  - OracleMenu
  - MenuItem
  - FormsProcedure
  - FormsFunction
  
  # Oracle Reports
  - OracleReport
  - ReportGroup
  - ReportQuery
  - ReportParameter
  - ReportLayout
  
  # Oracle APEX Conversion Entities
  - ConvertedOracleForm
  - ConvertedObjectLibrary
  - ConvertedMenuModule
  - PLSQLLibraryText
  - ApexConversionProject
  - ConversionMetadata
  
  # PL/SQL Entities
  - PLSQLPackage
  - PLSQLProcedure
  - PLSQLFunction
  - PLSQLCursor
  - PLSQLException
  - PLSQLType
  - PLSQLRecord
  - PLSQLCollection
  - PLSQLTrigger
  
  # Database Objects
  - OracleTable
  - OracleView
  - OracleMaterializedView
  - OracleSequence
  - OracleIndex
  - OracleTrigger
  - OracleConstraint
  - OracleSynonym
  
  # Database Schema Objects
  - OracleSchema
  - OracleTablespace
  - OracleUser
  - OracleRole
  - OraclePrivilege
  
  # Business and Data Flow
  - BusinessProcess
  - BusinessRule
  - DataFlow
  - BusinessEntity
  - DataModel
  - Transaction
  
  # Configuration
  - OracleConfiguration
  - DatabaseLink
  - ConnectionString
  - FormConfiguration
  
  # Documentation
  - Document
  - TechnicalSpecification
  - UserDocumentation
  - SystemDocumentation

# Relationship types allowed in the knowledge graph
# Format: Triple relationships as [source_node, relationship_type, target_node]
# This provides precise control over Oracle-specific entity relationships
allowed_relationships:
  # Oracle Forms Structure Relationships
  - [OracleForm, HAS_BLOCK, FormBlock]
  - [FormBlock, HAS_ITEM, FormItem]
  - [OracleForm, HAS_CANVAS, FormCanvas]
  - [OracleForm, HAS_TRIGGER, FormTrigger]
  - [FormBlock, HAS_TRIGGER, FormTrigger]
  - [FormItem, HAS_TRIGGER, FormTrigger]
  - [OracleForm, HAS_WINDOW, FormWindow]
  - [FormItem, HAS_LOV, FormLOV]
  - [OracleForm, HAS_ALERT, FormAlert]
  - [FormBlock, BELONGS_TO_FORM, OracleForm]
  - [FormItem, BELONGS_TO_FORM, OracleForm]
  
  # Forms Data Relationships
  - [FormBlock, BASED_ON_TABLE, OracleTable]
  - [FormBlock, BASED_ON_VIEW, OracleView]
  - [FormBlock, MASTER_DETAIL, FormBlock]
  - [FormItem, LOOKUP_TO, FormLOV]
  - [FormItem, REFERENCES_ITEM, FormItem]
  - [FormLOV, POPULATES_FROM, OracleTable]
  - [FormLOV, POPULATES_FROM, OracleView]
  
  # Forms Navigation and Execution
  - [OracleForm, NAVIGATES_TO, OracleForm]
  - [FormTrigger, CALLS_FORM, OracleForm]
  - [FormTrigger, OPENS_FORM, OracleForm]
  - [FormTrigger, CLOSES_FORM, OracleForm]
  - [OracleForm, PASSES_PARAMETER, FormParameter]
  
  # Oracle Libraries and Menus
  - [OracleLibrary, CONTAINS_PROCEDURE, FormsProcedure]
  - [OracleLibrary, CONTAINS_FUNCTION, FormsFunction]
  - [OracleForm, USES, OracleLibrary]
  - [OracleMenu, HAS_ITEM, MenuItem]
  - [MenuItem, CALLS_FORM, OracleForm]
  - [MenuItem, CALLS_PROCEDURE, FormsProcedure]
  
  # PL/SQL Package Relationships
  - [PLSQLPackage, CONTAINS_PROCEDURE, PLSQLProcedure]
  - [PLSQLPackage, CONTAINS_FUNCTION, PLSQLFunction]
  - [PLSQLPackage, CONTAINS_CURSOR, PLSQLCursor]
  - [PLSQLPackage, CONTAINS_EXCEPTION, PLSQLException]
  - [PLSQLProcedure, CALLS_PROCEDURE, PLSQLProcedure]
  - [PLSQLFunction, CALLS_FUNCTION, PLSQLFunction]
  - [PLSQLProcedure, USES_CURSOR, PLSQLCursor]
  - [PLSQLFunction, USES_CURSOR, PLSQLCursor]
  - [PLSQLProcedure, RAISES_EXCEPTION, PLSQLException]
  - [PLSQLFunction, RAISES_EXCEPTION, PLSQLException]
  - [PLSQLProcedure, HANDLES_EXCEPTION, PLSQLException]
  
  # Database Object Relationships
  - [OracleTable, BELONGS_TO_SCHEMA, OracleSchema]
  - [OracleView, BELONGS_TO_SCHEMA, OracleSchema]
  - [OracleSequence, BELONGS_TO_SCHEMA, OracleSchema]
  - [OracleIndex, BELONGS_TO_SCHEMA, OracleSchema]
  - [OracleTrigger, BELONGS_TO_SCHEMA, OracleSchema]
  - [OracleTable, HAS_INDEX, OracleIndex]
  - [OracleTable, HAS_TRIGGER, OracleTrigger]
  - [OracleTable, HAS_CONSTRAINT, OracleConstraint]
  - [OracleConstraint, REFERENCES_TABLE, OracleTable]
  - [OracleTable, FOREIGN_KEY_TO, OracleTable]
  
  # Data Access Relationships
  - [PLSQLProcedure, SELECTS_FROM, OracleTable]
  - [PLSQLFunction, SELECTS_FROM, OracleTable]
  - [PLSQLProcedure, INSERTS_INTO, OracleTable]
  - [PLSQLProcedure, UPDATES, OracleTable]
  - [PLSQLProcedure, DELETES_FROM, OracleTable]
  - [PLSQLProcedure, USES_SEQUENCE, OracleSequence]
  - [PLSQLFunction, USES_SEQUENCE, OracleSequence]
  - [FormBlock, ACCESSES_TABLE, OracleTable]
  - [FormBlock, QUERIES_VIEW, OracleView]
  - [OracleView, SELECTS_FROM, OracleTable]
  
  # Oracle Reports Relationships
  - [OracleReport, HAS_GROUP, ReportGroup]
  - [ReportGroup, HAS_QUERY, ReportQuery]
  - [OracleReport, HAS_PARAMETER, ReportParameter]
  - [OracleReport, HAS_LAYOUT, ReportLayout]
  - [ReportQuery, SELECTS_FROM, OracleTable]
  - [ReportQuery, SELECTS_FROM, OracleView]
  
  # Dependencies and Usage
  - [OracleForm, DEPENDS_ON, PLSQLPackage]
  - [FormsProcedure, DEPENDS_ON, PLSQLPackage]
  - [PLSQLPackage, DEPENDS_ON, PLSQLPackage]
  - [OracleForm, USES, OracleSequence]
  - [FormTrigger, USES, PLSQLFunction]
  - [FormTrigger, USES, PLSQLProcedure]
  
  # Business Process Relationships
  - [BusinessProcess, PROCESSES, BusinessEntity]
  - [OracleForm, MANAGES, BusinessEntity]
  - [FormTrigger, HANDLES, BusinessRule]
  - [PLSQLPackage, SUPPORTS, BusinessProcess]
  - [FormItem, VALIDATES, BusinessEntity]
  - [PLSQLFunction, CALCULATES, BusinessEntity]
  - [PLSQLProcedure, TRANSFORMS, DataModel]
  
  # Execution and Control Flow
  - [FormTrigger, EXECUTES, PLSQLProcedure]
  - [FormTrigger, TRIGGERS, FormTrigger]
  - [PLSQLTrigger, FIRES, PLSQLProcedure]
  - [Transaction, RUNS, PLSQLProcedure]
  - [PLSQLProcedure, COMMITS, Transaction]
  - [PLSQLProcedure, ROLLBACKS, Transaction]
  
  # Configuration Relationships
  - [OracleConfiguration, CONFIGURES, OracleForm]
  - [FormConfiguration, CONFIGURES, FormBlock]
  - [ConnectionString, CONNECTS_TO, OracleSchema]
  - [DatabaseLink, USES_LINK, OracleSchema]
  - [FormConfiguration, SETS_PROPERTY, FormItem]
  
  # Documentation Relationships
  - [TechnicalSpecification, DOCUMENTS, OracleForm]
  - [UserDocumentation, DESCRIBES, OracleForm]
  - [SystemDocumentation, DESCRIBES, PLSQLPackage]
  - [TechnicalSpecification, SPECIFIES, FormBlock]
  - [UserDocumentation, EXPLAINS, BusinessProcess]
  
  # APEX Conversion Relationships
  - [ConvertedOracleForm, CONVERTED_FROM, OracleForm]
  - [ConvertedObjectLibrary, CONVERTED_FROM, OracleLibrary]
  - [ConvertedMenuModule, CONVERTED_FROM, OracleMenu]
  - [PLSQLLibraryText, CONVERTED_FROM, OracleLibrary]
  - [ConvertedOracleForm, PART_OF_CONVERSION, ApexConversionProject]
  - [ConvertedOracleForm, XML_REPRESENTS, OracleForm]
  - [ConversionMetadata, PRESERVES_METADATA, OracleForm]
  - [ConvertedOracleForm, MAPS_TO_APEX_COMPONENT, ApexConversionProject]